TARGET = MiniTRX-client
TEMPLATE = app
QT += qml quick multimedia websockets
CONFIG += static
QMAKE_LFLAGS += -static
OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build
RESOURCES = qml/MiniTRX-client.qrc
HEADERS = client.h grid.h spectrum.h waterfall.h
SOURCES = client.cpp grid.cpp spectrum.cpp waterfall.cpp main.cpp
