TARGET = MiniTRX-client
TEMPLATE = app
QT += uitools multimedia websockets
CONFIG += static
INCLUDEPATH += /opt/soxr/soxr-0.1.1-win32/include
LIBS += -L/opt/soxr/soxr-0.1.1-win32/lib -lsoxr
QMAKE_LFLAGS += -static
RESOURCES = client.qrc
HEADERS = client.h indicator.h plotter.h
SOURCES = client.cpp indicator.cpp plotter.cpp main.cpp
