TARGET = MiniTRX-client
TEMPLATE = app
QT += uitools multimedia websockets
CONFIG += static
QMAKE_LFLAGS += -static
OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build
RESOURCES = client.qrc
HEADERS = client.h indicator.h plotter.h
SOURCES = client.cpp indicator.cpp plotter.cpp main.cpp
