TARGET = MiniTRX-server
QT += core websockets
QT -= gui
CONFIG += static console debug_and_release
TEMPLATE = app
QMAKE_CFLAGS = -ffast-math
INCLUDEPATH += ../wdsp /opt/fftw/fftw-3.2.2-armhf/include
LIBS += -L../wdsp -lwdsp -L/opt/fftw/fftw-3.2.2-armhf/lib -lfftw3f
QMAKE_LFLAGS += -static
HEADERS = server.h
SOURCES = server.cpp main.cpp
